### ISSUE TITLE
Letterboxd support

### ISSUE THREAD

**Issue by ronilaukkarinen** [RemiRigal/Overseerr-Assistant#1]
Can you add support for [Letterboxd](https://letterboxd.com/)?

**Comment by RemiRigal** [comment]
Hi @ronilaukkarinen ! Do you want `Overseerr Assistant` to support Letterboxd or do you want another similar extension for Letterboxd ?

**Comment by ronilaukkarinen** [comment]
Overseer Assistant could support it, better to have multiple movie sites in the same extension in my opinion.

**Comment by RemiRigal** [comment]
Ok thanks for the suggestion, I'm adding it to the roadmap.

**Comment by RemiRigal** [comment]
Hi @ronilaukkarinen ! Letterboxd support is finally here, you can try it out as soon as version v1.2.0 is available in the store (should be the case in a few hours), let me know if it works as expected !
Thank you for your patience.

**Comment by ronilaukkarinen** [comment]
@RemiRigal Awesome! Just tested it out and it works wonders. Thanks a lot!
