### ISSUE TITLE
Issue - Clicking "processing" link does not take you directly to a title in Overseerr like it should.

### ISSUE THREAD

**Issue by skynet01** [RemiRigal/Overseerr-Assistant#11]
Once movie has been requested it shows as processing on Imdb or Tvdb etc. However clicking the button only takes you to the root of Overseerr and not to the movie directly as it should. I see a login screen briefly for a split second before it takes me to the main dashboard.

I verified that the url for "processing" is correct (ex: http://sub.mydomain.com:111/movie/414906) when I hover over the button. Copying that url to clipboard and manually pasting it works properly.   

Thank youuzzzz :)

**Comment by RemiRigal** [comment]
Hi @skynet01, thank you for the bug report !
I've been experiencing this issue for a few weeks now, it seems to be caused by the authentication method used in Overseerr. I don't know why it doesn't work when you click on the link in the button and it's fine when you copy/paste the link in the browser though. I will investigate further as this needs to be addressed.

**Comment by skynet01** [comment]
Hmm.. is there maybe an API call to Overseerr with a movie id and then the redirect is done by Overseerr itself and not by direct link from extension? .. or maybe some other way to do a redirect .. just throwing some ideas ..

**Comment by RemiRigal** [comment]
@binitGajera thank you for taking the time to investigate this, you are indeed correct. When I change the `SameSite` policy of my `connect.sid` cookie to `Lax` it does work as expected.

I will create an issue on their side to either change the `SameSite` policy or at least add an option in the settings to change it.

**Comment by RemiRigal** [comment]
The PR I submitted this morning has been merged on the `develop` branch of the Overseerr project already. The feature will probably be released with the upcoming version but if you want to give it a shot you can upgrade your Overseerr instance to the `develop` version.

I just tried it works well, you just have to make sure that the CSRF Protection is disabled in the settings (it's disabled by default). Closing this issue for now, but feel free to reopen it if the problem persists.
