### ISSUE TITLE
Movies with special characters

### ISSUE THREAD

**Issue by ronilaukkarinen** [RemiRigal/Overseerr-Assistant#13]
1. Test a movie with exclamation mark, for example [Ach du Scheisse!](https://www.imdb.com/title/tt13947858/)
2. See the plugin stuck:

![image](https://user-images.githubusercontent.com/1534150/163552348-acf88662-af7e-41a5-82b5-36ead34941bf.png)

Console:

![image](https://user-images.githubusercontent.com/1534150/163552271-5c23d114-23b0-4ab8-b28f-3c757b790b55.png)

**Comment by RemiRigal** [comment]
Good catch ! The `encodeURIComponent` function [do escape some characters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#description) including '!'.
This one is an easy fix, I just need to check if this can happen with other characters. Thank you for the issue !
