### ISSUE TITLE
Error handling response: TypeError: Cannot read properties of undefined (reading 'localeCompare')

### ISSUE THREAD

**Issue by ronilaukkarinen** [RemiRigal/Overseerr-Assistant#14]
For some reason doesn't work at the moment. Version: 1.3.1.

Tested URL: https://www.imdb.com/title/tt9172960/

![image](https://user-images.githubusercontent.com/1534150/163674751-04505a05-6864-4c9c-be62-d366bc36f60e.png)

**Comment by RemiRigal** [comment]
Fixed by [817e202](https://github.com/RemiRigal/Overseerr-Assistant/commit/817e2023c1113aa578385b7445232752c3bc5948) in v1.3.2, thank you for the issue !
