### ISSUE TITLE
Letterboxd support not working properly

### ISSUE THREAD

**Issue by ayykamp** [RemiRigal/Overseerr-Assistant#15]
The letterboxd formatting gets messed up
![image](https://user-images.githubusercontent.com/32194363/167679436-5106746b-7f3f-472b-87bf-8febfddd1204.png)
vs How it should look
![image](https://user-images.githubusercontent.com/32194363/167679519-5b040c4c-b533-4ed0-8abe-dfabb0d05c49.png)

**Comment by RemiRigal** [comment]
Thank you for pointing this out, I will fix this !

**Comment by seanecoffey** [comment]
Adding `document.querySelector(`.truncate`).classList.remove(`truncate`);` to letterboxd.js prevents text truncation:
![image](https://user-images.githubusercontent.com/18379288/171332897-9e1a646d-1974-4598-8778-991c8a2a2b40.png)
On initial testing this doesn't seem to mess with formatting - though not sure this is the ideal solution?

**Comment by ayykamp** [comment]
Looks good to me! Thanks for fixing :)
