### ISSUE TITLE
Just Watch support?

### ISSUE THREAD

**Issue by milogert** [RemiRigal/Overseerr-Assistant#20]
Would there be any interest in integrating this into [Just Watch](https://justwatch.com)? I frequently use that site to determine if I should request a movie or not and this seems like the perfect integration for that.

**Comment by RemiRigal** [comment]
Hi @milogert, thank you for your suggestion ! I've added support for `JustWatch` in version `v1.4.2` that should be available in the next few hours. Let me know if it suits your needs !

**Comment by milogert** [comment]
Perfect! That's great. Thanks for the addition

**Comment by ronilaukkarinen** [comment]
I don't see any button in Just Watch single movies? Random [example](https://www.justwatch.com/fi/elokuva/the-hitmans-wifes-bodyguard).

**Comment by RemiRigal** [comment]
> I don't see any button in Just Watch single movies? Random [example](https://www.justwatch.com/fi/elokuva/the-hitmans-wifes-bodyguard).

I do see it in the page you linked:
![image](https://user-images.githubusercontent.com/19256051/189492571-0cbe2956-515e-4184-82fb-749aab8efdac.png)

Are you sure that the extension is enabled ? If yes, do you anything in the browser console ?
