### ISSUE TITLE
Adding Overseerr server without port? (behind reverse proxy)

### ISSUE THREAD

**Issue by rh535** [RemiRigal/Overseerr-Assistant#22]
Is it possible to add your Overseerr which is behind a reverse proxy? I can't seem to leave it blank. It saves their information then when I reload the extension it adds 8001 in the port field and a slash in the path field.

**Comment by RemiRigal** [comment]
Every URL has a port, you just usually don't see it because it uses default ports. Default ports for HTTP and HTTPS are `80` and `443` respectively, can you try one of those values depending on the scheme you are using ?

**Comment by rh535** [comment]
That worked. Thank you!
