### ISSUE TITLE
Enhancement Request: Trakt.TV support?

### ISSUE THREAD

**Issue by marc-cwm** [RemiRigal/Overseerr-Assistant#29]
Any possibility of adding functionality for Trakt to this extension?

**Comment by RemiRigal** [comment]
Hi @marc-cwm, thank you for your suggestion ! I've added support for Trakt.tv in version v1.5.0 , let me know if it suits your needs.

**Comment by marc-cwm** [comment]
Wow, that's perfect, good placement too, thank you!
