### ISSUE TITLE
Allow adding overseerr running in a subdirectory

### ISSUE THREAD

**Issue by ronilaukkarinen** [RemiRigal/Overseerr-Assistant#3]
I run my overseerr as per:

https://github.com/coder8338/appbox_installer/blob/c58e0d640dc517ab539c7a2ce8962b2fad34f983/appbox_installer.sh#L950

Can you add support to this structure? For example test.test.test.me/overseerr

Thanks!

**Comment by RemiRigal** [comment]
I will add this possibility yes.

**Comment by RemiRigal** [comment]
As of version v1.2.0 you can now setup a custom path in the `options` page ! I'm closing this issue but feel free to reopen it if you encounter any issues.
