### ISSUE TITLE
Letterboxd support broken

### ISSUE THREAD

**Issue by cbritopacheco** [RemiRigal/Overseerr-Assistant#31]
I am on Overseer 1.31.0. 

# Problem
Clicking on "Request":
![Capture](https://user-images.githubusercontent.com/6352283/213580644-b4918baa-396c-499b-861c-c0283977572e.PNG)

Just outputs "Error" and the movie is not requested:
![error](https://user-images.githubusercontent.com/6352283/213580700-525fb250-44f0-41cf-93ee-cafc3fca1dd6.PNG)

This is what setup options look like:
![Capture](https://user-images.githubusercontent.com/6352283/213580928-ca76ca19-31f6-4723-b28f-866b5ee98ee6.PNG)

# Notes

All the Overseer status appear to be working correctly, ie. it correctly shows that the movie is available, or processing.

**Comment by RemiRigal** [comment]
Hi @cbritopacheco, thank you for the detailed issue.

I've tried to request the exact same show from Letterboxd and it works without issues on my hand.
Could you try the following:
- Go to the `Extensions` settings page of Chrome
- Locate `Overseerr Assistant` and click on the `service worker` link
- A new page should appear, go to the `Network` tab
- In the original Chrome window, go back to Letterboxd and click again on `Request`
- In the service worker window, click on the line called `request` (in case you have multiple, pick the last one)
- Check the `Response` tab of the request and send me anything that looks relevant
- Check that you have the following line in the console: `Requesting media '819876' of type 'movie'`

Let me know if you need additional information.

**Comment by cbritopacheco** [comment]
Seems that the CSRF token is invalid.

Test case: https://letterboxd.com/film/the-fabelmans/

Response:

```json
{"message":"invalid csrf token"}
```

Request Payload:

```json
{"mediaType":"movie", "mediaId":804095, "seasons":[]}
```

General

```
Request URL: [REDACTED]
Request Method: POST
Status Code: 403 
Remote Address: [REDACTED]:443
Referrer Policy: strict-origin-when-cross-origin
```

Response Headers

```
content-length: 32
content-type: application/json; charset=utf-8
date: [REDACTED]
etag: [REDACTED]
server: openresty
strict-transport-security: [REDACTED]
x-powered-by: Express
```

Request Headers

```
:authority: [REDACTED]
:method: POST
:path: /api/v1/request
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7,es-MX;q=0.6,es;q=0.5
content-length: 51
content-type: application/json
cookie: connect.sid=[REDACTED]
dnt: 1
origin: [REDACTED]
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: none
user-agent: [REDACTED]
x-api-key: [REDACTED]
```

**Comment by cbritopacheco** [comment]
Update: It was the CSRF protection in Overseer which I had enabled.

Go to Overseer and untick the box for:
```
Settings > Enable CSRF Protection
```

Thank you for the awesome extension!
