### ISSUE TITLE
Add support for Rotten Tomatoes

### ISSUE THREAD

**Issue by azuravian** [RemiRigal/Overseerr-Assistant#32]
Would it be possible to add Rotten Tomatoes as one of the supported sites?

**Comment by RemiRigal** [comment]
Thank you for the suggestion @azuravian. Sure, Rotten Tomatoes should be supported as well, will work on this !

**Comment by RemiRigal** [comment]
Rotten Tomatoes support added in `v1.5.1`, let me know if it suits your needs !

**Comment by azuravian** [comment]
Perfect, thank you!

**Comment by jeliastam** [comment]
did this break or can I just not find the button

**Comment by randalotto** [comment]
> did this break or can I just not find the button

Doesn't seem to be working for me, either.
