### ISSUE TITLE
Support for Overseerr with only a domain (no port, no path)

### ISSUE THREAD

**Issue by Hollander-1908** [RemiRigal/Overseerr-Assistant#38]
It is not possible to use Overseerr with a domain without specifying a port or path.
When I save it without port and path it will say it succesfully connected but when I reload the settings it has been fallback to port `8001` and path `/`, this way I cannot use the extension unfortunately.

Edit: Changed it in `storage.js` in the meantime to get it to work.

**Comment by RemiRigal** [comment]
This is intended yes, could you try setting the path variable to `/` and the port to either 80 or 443 for http and https respectively ? It should work with this configuration.
However, I do agree that the user experience would benefit from having these fields as optional, I will work on it. Thanks a lot for the precious feedback !

**Comment by Hollander-1908** [comment]
Well my domain is accessed trough Cloudflare so that won't work. Because the domain would be `https://sub.domain.com:80/` in that case. 

If you make it optional it would be wonderful. As I said I changed it to blank in `storage.js` and that worked for me.

**Comment by RemiRigal** [comment]
To clarify, querying `https://sub.domain.com/` and `https://sub.domain.com:443/` is exactly the same thing, the port is usually omitted for readability but your browser will send every HTTPS requests to port 443 anyway (same applies for HTTP and port 80). I get that it works when you modify `storage.js` but you may no longer receive updates on the extension which is not ideal. 

I can guarantee you that it will work if you use the following configuration, even with CloudFlare, and it's in your best interest as well:
- Path: `/`
- Port: `443`
- Use HTTPS: `true`

But again, I get that it can be confusing and I will update the UI accordingly.

**Comment by Hollander-1908** [comment]
You're totally right, that works as well! 
Using te Chrome extension again. Thanks a lot! :)
