### ISSUE TITLE
Allow using it without port configured

### ISSUE THREAD

**Issue by fscorrupt** [RemiRigal/Overseerr-Assistant#4]
im running my Overseerr with my own domain over CloudFlare, and behind a proxy, so i cant specify the port in my configuration.

**my url is:** https://overseerr.domain.com
**my api call would be:** https://overseerr.domain.com/api/v1/auth/me

But your config needs a port, and always sets it back to default when i save it without port.

**Comment by RemiRigal** [comment]
Hi @fscorrupt ! Port is required yes, in your case you must set the port to 443, which is the defaut HTTPS port. Let me know !
