### ISSUE TITLE
IMDB broken

### ISSUE THREAD

**Issue by NetixQc** [RemiRigal/Overseerr-Assistant#40]
Seems like it's broken for IMDB ? Doesn't show anymore on anything on IMDB.

Works wells with other website.

**Comment by RemiRigal** [comment]
Thanks for reporting the issue, the next update (version `1.5.6`) will fix this. Let me know if it works for you then.

**Comment by NetixQc** [comment]
Seems like IMDB is broken again.

**Comment by joseluislucas** [comment]
Broken to me too (I'm running 1.5.6)

**Comment by joseluislucas** [comment]
Solved on 1.5.7, thanks!
