### ISSUE TITLE
Add Plex Discover Support

### ISSUE THREAD

**Issue by fscorrupt** [RemiRigal/Overseerr-Assistant#8]
Can you add support for [Plex Discover](https://support.plex.tv/articles/discover/) ?

**Comment by RemiRigal** [comment]
Hi @fscorrupt, can you describe the kind of support you are looking for ? I just want to be sure to understand the use case you have in mind.

**Comment by fscorrupt** [comment]
Hey, yeah sure.
with the new discover feature you can now search in plex for every movie/show, even if its not in your lib, it would be nice to have plugin support on the discovery page to make requests directly from plex web.

**Comment by skynet01** [comment]
Love this idea btw :)

**Comment by RemiRigal** [comment]
I've added Plex Discover support in the version v1.3.0 of the extension. Please try it out and let me know if everything works as expected. Enjoy ! 😃

**Comment by fscorrupt** [comment]
wow, that was fast 😅
will have a look tomorrow!
thanks

**Comment by fscorrupt** [comment]
hey, played a bit today works really well!
But i found a Show that does get request as another one..

![image](https://user-images.githubusercontent.com/45659314/163528825-214ab336-7a9d-4a82-a140-972eff0bcd6a.png)

**Comment by RemiRigal** [comment]
This one was a tough one as Plex uses its own identifiers for movies and tv shows so I was using a title based search that can lead to mismatches like the one you mentioned.
After some experiments I found a way to extract the TMDB id from Plex and it seems to do the trick. If any of you can give me some feedback it would be great, thank you in advance ! (Make sure your extension is updated to v1.3.1 beforehand)

**Comment by fscorrupt** [comment]
thanks again for the fast fix, I will test it intensively in the next few days! Rg

**Comment by fscorrupt** [comment]
tried a bit with version 1.3.2.
i get on every show and movie **media not found**.
![image](https://user-images.githubusercontent.com/45659314/163937004-ab9a0ed8-eb93-4aee-8621-a9f844f7e78e.png)

**Comment by fscorrupt** [comment]
this is the complete Url: [OuterRange](https://app.plex.tv/desktop/#!/provider/tv.plex.provider.metadata/details?key=%2Flibrary%2Fmetadata%2F5fc66a1302769b002d93d328&context=search%3Ahub.external~2~0)

and i have `X-Plex-Token` with my token in it.

**Comment by fscorrupt** [comment]
Fixed it with adding my server ip to custom server access url. it now works without problems. Thanks again!
